apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuber
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development     # это то,что создали выше в dev.yaml

  source:   # из какого репозитория брать исходный код 
    repoURL: https://github.com/Wireflex/Kubernetes.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: main  # For Helm, this refers to the chart version.
    path: ArgoCD/dev/kuber  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

  destination:    # куда деплоим (у нас только 1 дефолтный)
    server: https://kubernetes.default.svc
    namespace: kuber    # этого намспейса пока нет, но ниже в CreateNamespace создадим

  syncPolicy:    # используется для автоматического обнаружния коммитов ArgoCD, будет чекать каждые 3 минуты
    automated: # можно указать manual и тогда вручную нужно будет начинать CD
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
